server:
  port: 8080

spring:
  application:
    name: ocean-protection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ocean_protection?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 20012001
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never
      continue-on-error: false
  mvc:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  main:
    allow-circular-references: true

# JWT配置
jwt:
  secret: "your-256-bit-secret-key-here-must-be-longer-than-256-bits"
  expiration: 86400  # 24小时

# 自定义配置
app:
  image:
    storage-path: /Users/wang/Downloads/code/海洋动物保护/ocean-images

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  type-aliases-package: com.ocean.protection.entity
  mapper-locations: classpath*:/mapper/*.xml 